###Render TRY PLAYERS
https://cse341-projectweek3-munives.onrender.com/players/

###Render TRY TEAMS
https://cse341-projectweek3-munives.onrender.com/teams/

### TRY RENDER API-DOCS
https://cse341-projectweek3-munives.onrender.com/api-docs

